-- Create Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'pending' check (status in ('pending', 'processing', 'completed', 'cancelled')),
  total_amount numeric not null,
  items jsonb not null, -- Stores snapshot of ordered items
  customer_details jsonb not null, -- Stores name, email, phone, address
  
  -- Optional: link to booking or user if we had auth for customers
  booking_id bigint references public.bookings(id)
);

-- Enable RLS
alter table public.orders enable row level security;

-- Policies

-- Public can create orders (during checkout)
create policy "Public can create orders" on public.orders
  for insert with check (true);

-- Admins can view/update all orders
create policy "Admins can manage all orders" on public.orders
  for all to authenticated using (true);
