-- Create Menu Items Table
-- Create Menu Items Table
create table public.menu_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null,
  category text not null, -- 'Starters', 'Mains', 'Desserts', 'Drinks'
  image text,
  tags text[], -- Array of strings e.g. ['Vegan', 'GF']
  is_available boolean default true
);

-- Create Bookings Table
create table public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null,
  time text not null,
  party_size integer not null,
  name text not null,
  email text not null,
  phone text not null,
  requests text,
  status text default 'pending' -- 'pending', 'confirmed', 'cancelled'
);

-- Enable Row Level Security (RLS)
alter table public.menu_items enable row level security;
alter table public.bookings enable row level security;

-- Policies for Menu Items
-- Public read access
create policy "Public items are viewable by everyone" on public.menu_items
  for select using (true);

-- Admin write access (Authenticated users only)
create policy "Authenticated users can insert items" on public.menu_items
  for insert with check (auth.role() = 'authenticated');
  
create policy "Authenticated users can update items" on public.menu_items
  for update using (auth.role() = 'authenticated');

create policy "Authenticated users can delete items" on public.menu_items
  for delete using (auth.role() = 'authenticated');


-- Policies for Bookings
-- Public can create bookings
create policy "Public can create bookings" on public.bookings
  for insert with check (true);

-- Only authenticated users (admins) can view all bookings
create policy "Authenticated users can view bookings" on public.bookings
  for select using (auth.role() = 'authenticated');

-- Allow updates to booking status (Authenticated users only)
create policy "Authenticated users can update bookings" on public.bookings
  for update using (auth.role() = 'authenticated');
-- Reviews Table
create table public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  name text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected'))
);

-- RLS Policies for Reviews
alter table public.reviews enable row level security;

-- Public can read ONLY approved reviews
create policy "Public can view approved reviews"
on public.reviews
for select
to public
using (status = 'approved');

-- Public can insert new reviews (they start as pending)
create policy "Public can submit reviews"
on public.reviews
for insert
to public
with check (status = 'pending');

-- Admin can do everything
create policy "Admins can manage all reviews"
on public.reviews
for all
to authenticated
using (true);
